version: "3.8"
services:
  mysql:
    image: mysql:8.0.32
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3306:3306'
    volumes:
      - $PWD/conf/mysql/data:/var/lib/mysql
  ws:
    image: openltablets/ws:5.26.6
    ports:
      - 8080:8080
    environment:
      - production-repository.factory=repo-jdbc
      - production-repository.uri=jdbc:mysql://mysql:3306/test
      - production-repository.login=root
      - production-repository.password=mysql
    volumes:
      - $PWD/conf/service/jdbc/mysql-connector-j-8.0.32.jar:/opt/openl/lib/jdbc.jar
    depends_on:
      - mysql
  webstudio:
    image: openltablets/webstudio:5.26.6
    ports:
      - 8081:8080
    volumes:
      - $PWD/conf/studio/jdbc/mysql-connector-j-8.0.32.jar:/opt/openl/lib/jdbc.jar
      - $PWD/conf/studio/local:/opt/openl/local
